"use client";

import { EventData } from "@/lib/api";
import { memo, useMemo } from "react";
import { useLocale } from "@/lib/locale-context";
import { DecodeText } from "./ui";

/**
 * ChronicleView — one chapter per tick, one POV character.
 * Each chapter is a full narrative passage generated by the narrator LLM.
 * Read top-to-bottom = read a novel.
 */

const ChapterEntry = memo(function ChapterEntry({
  event,
  index,
  isNew,
}: {
  event: EventData;
  index: number;
  isNew?: boolean;
}) {
  return (
    <article
      className={`border-b border-b-DEFAULT ${isNew ? "animate-[fade-in_500ms_ease]" : ""}`}
    >
      {/* Chapter heading */}
      <div className="px-6 pt-6 pb-3 flex items-baseline justify-between">
        <span className="text-micro text-t-dim tracking-widest tabular-nums">
          {String(index + 1).padStart(2, "0")}
        </span>
        <h3 className="text-t-DEFAULT text-detail font-medium tracking-wider normal-case flex-1 text-center">
          {event.agent_name}
        </h3>
        <span className="text-micro text-t-dim tracking-wider tabular-nums">
          T{String(event.tick).padStart(3, "0")}
        </span>
      </div>

      {/* Chapter body */}
      <div className="px-8 pb-6">
        <div className="text-detail text-t-secondary normal-case tracking-normal leading-[1.9] break-words whitespace-pre-line">
          {isNew ? <DecodeText text={event.result} /> : event.result}
        </div>
      </div>
    </article>
  );
});

const RENDER_WINDOW = 100;

export default function ChronicleView({
  events,
  newEventIds,
  isRunning,
}: {
  events: EventData[];
  newEventIds?: Set<string>;
  isRunning?: boolean;
}) {
  const { t } = useLocale();

  const chapters = useMemo(
    () => events.filter((e) => e.action_type === "chapter"),
    [events],
  );

  const windowed = useMemo(
    () =>
      chapters.length > RENDER_WINDOW
        ? chapters.slice(-RENDER_WINDOW)
        : chapters,
    [chapters],
  );

  const indexOffset = chapters.length - windowed.length;

  if (chapters.length === 0 && !isRunning) {
    return (
      <div className="flex items-center justify-center py-16 text-micro text-t-dim tracking-widest">
        {t("chronicle_empty")}
      </div>
    );
  }

  return (
    <div className="flex flex-col" role="log" aria-label="Chronicle">
      {windowed.map((event, i) => (
        <ChapterEntry
          key={event.id}
          event={event}
          index={indexOffset + i}
          isNew={newEventIds?.has(event.id)}
        />
      ))}
      {isRunning && (
        <div className="px-6 py-8 text-center">
          <span className="text-micro text-t-muted tracking-widest animate-pulse">
            {t("chapter_writing")}
          </span>
        </div>
      )}
    </div>
  );
}
